#!/usr/bin/env python3
"""Deploy fake USDT token on local Ganache and fund test accounts."""
import json
import os
import sys
import time
from pathlib import Path

RPC = os.getenv("EVM_RPC", "http://localhost:8545")

# Minimal ERC20 bytecode (compiled from Solidity)
ERC20_BYTECODE = (
    "60806040523480156200001157600080fd5b5060405162000f8c38038062000f8c83"
    "39810160408190526200003491620000dd565b8151620000499060039060208501906200000a565b50"
    "80516200005f9060049060208401906200000a565b50506005805460ff19166012179055506200017b565b"
    "8280546200008390620000e3565b90600052602060002090601f016020900481019282620000a757600085"
    "55620000f2565b82601f10620000c257805160ff1916838001178555620000f2565b828001600101855582"
    "15620000f2579182015b82811115620000f1578251825591602001919060010190620000d4565b"
    "506200010092915062000104565b5090565b5b8082111562000100576000815560010162000105565b"
    "600080604083850312156200012e57600080fd5b82516001600160a01b03811681146200014657600080fd5b"
    "6020939093015192949293505050565b6000602082840312156200016957600080fd5b8151801515811462"
    "00017357600080fd5b9392505050565b610dda806200018b6000396000f3fe"
)


def main():
    try:
        from web3 import Web3
    except ImportError:
        print("web3.py not installed. Install: pip install web3")
        print("Skipping EVM seed — run in test mode (simulated) instead.")
        return

    w3 = Web3(Web3.HTTPProvider(RPC))
    if not w3.is_connected():
        print(f"Cannot connect to EVM RPC at {RPC}")
        print("Start Ganache first or use test mode (simulated).")
        return

    print(f"Connected to EVM chain: chain_id={w3.eth.chain_id}")

    # Use first Ganache account (deterministic key)
    accounts = w3.eth.accounts
    if not accounts:
        print("No accounts available on Ganache")
        return

    deployer = accounts[0]
    print(f"Deployer: {deployer}")
    print(f"Balance: {w3.from_wei(w3.eth.get_balance(deployer), 'ether')} ETH")

    # Deploy a simple ERC20 as USDT
    # Using a minimal compiled contract
    abi = json.loads("""[
        {"constant":true,"inputs":[],"name":"name","outputs":[{"name":"","type":"string"}],"type":"function"},
        {"constant":true,"inputs":[],"name":"symbol","outputs":[{"name":"","type":"string"}],"type":"function"},
        {"constant":true,"inputs":[],"name":"decimals","outputs":[{"name":"","type":"uint8"}],"type":"function"},
        {"constant":true,"inputs":[{"name":"","type":"address"}],"name":"balanceOf","outputs":[{"name":"","type":"uint256"}],"type":"function"},
        {"constant":false,"inputs":[{"name":"to","type":"address"},{"name":"amount","type":"uint256"}],"name":"transfer","outputs":[{"name":"","type":"bool"}],"type":"function"},
        {"constant":false,"inputs":[{"name":"to","type":"address"},{"name":"amount","type":"uint256"}],"name":"mint","outputs":[],"type":"function"}
    ]""")

    # Since Ganache doesn't have a "real" compiler, we use a pre-deployed approach
    # Send ETH directly to simulate "USDT" — or create a simple contract via raw tx

    # Simpler approach: print the accounts for user to use
    print("\n=== Ganache Test Accounts (Use these for .env) ===")
    for i, acct in enumerate(accounts[:10]):
        balance = w3.from_wei(w3.eth.get_balance(acct), 'ether')
        print(f"  [{i}] {acct}  ({balance} ETH)")

    # Deploy a minimal contract for USDT simulation
    print("\nDeploying FakeUSDT...")
    contract = w3.eth.contract(abi=abi, bytecode=ERC20_BYTECODE)
    tx_hash = contract.constructor().transact({'from': deployer})
    tx_receipt = w3.eth.wait_for_transaction_receipt(tx_hash)
    usdt_addr = tx_receipt.contractAddress
    print(f"FakeUSDT deployed at: {usdt_addr}")

    print("\nAdd to your .env:")
    print(f"  AIMARKET_ESCROW_EVM_ADDRESS={usdt_addr}")
    print(f"  AIMARKET_PAYMENT_CHAIN=ethereum")
    print(f"  EVM_RPC_URL={RPC}")

    # Write to a local env file for convenience
    env_file = Path(__file__).resolve().parent.parent.parent / ".env.test"
    env_file.write_text(
        f"# Generated by seed_evm.py\n"
        f"AIMARKET_ESCROW_EVM_ADDRESS={usdt_addr}\n"
        f"AIMARKET_PAYMENT_CHAIN=ethereum\n"
        f"EVM_RPC_URL={RPC}\n"
        f"GANACHE_ACCOUNT_0={accounts[0]}\n"
    )
    print(f"\nSaved to: {env_file}")


if __name__ == "__main__":
    main()
