"""The lottery moving out from under the relayer.

The UNI bubble re-bootstraps its Anvil from scratch now and then; every contract is
redeployed at a new address. The relayer resolved its address ONCE at startup, so it kept
calling `openRound()` at an address that no longer held code — which does not revert. It
"succeeds", burns 21160 gas and does nothing, so the relayer looked healthy while the
lottery it was driving no longer existed (once for nine days, found only when the chain
scanner was built). These tests pin the resolution and the mid-flight re-bind.
"""
from __future__ import annotations

from types import SimpleNamespace
from unittest.mock import MagicMock

from ailottery_relayer.config import Config, read_address_source
from ailottery_relayer.economy import EconomyEngine

LIVE = "0xdc64a140aa3e981100a9beca4e685f962f0cf6c9"
DEAD = "0x7635385340f52ee0f81b11c59ff10773818b94ff"
OTHER = "0xa513e6e4b8f2a923d98304ec87f64353c4d5c853"


# ── reading whatever shape the deploy step wrote ──────────────────────────────────────
def test_reads_a_bare_address_file(tmp_path):
    p = tmp_path / "lottery.address"
    p.write_text(f"{LIVE}\n")
    assert read_address_source(str(p)) == {"lottery": LIVE}


def test_reads_the_uni_env_snippet_including_the_hub_binding(tmp_path):
    """The real `hub.env.snippet`: comments, unrelated keys, and the lottery spelled three
    ways. A wrapper that grepped for exactly `^LOTTERY_ADDRESS=` fell through to a hardcoded
    address whenever the snippet led with the HUB_ variant."""
    p = tmp_path / "hub.env.snippet"
    p.write_text(
        "# Generated by Alien Monitor UNI bootstrap\n"
        "AIMARKET_ESCROW_EVM_ADDRESS=0xe7f1725e7734ce288f8367e1bb143e90bb3f0512\n"
        "# FakeUSDT on Anvil: 0x5fbdb2315678afecb367f032d93f642f64180aa3\n"
        f"HUB_LOTTERY_ADDRESS={LIVE}\n"
        f"AIMARKET_CHARITY_LOTTERY_ADDRESS={LIVE}\n"
        f"LOTTERY_ADDRESS={LIVE}   # the operating lottery\n"
        "LOTTERY_CHAIN_ID=31337\n"
    )
    assert read_address_source(str(p)) == {"lottery": LIVE, "hub": LIVE}


def test_reads_the_universe_json_config(tmp_path):
    p = tmp_path / "universe_config.json"
    p.write_text('{"evm_usdt": "0x5fbdb2315678afecb367f032d93f642f64180aa3", '
                 f'"evm_lottery": "{LIVE}"}}')
    assert read_address_source(str(p)) == {"lottery": LIVE}


def test_an_unreadable_or_junk_source_is_no_answer_never_an_exception(tmp_path):
    assert read_address_source(str(tmp_path / "nope")) == {}
    assert read_address_source(str(tmp_path)) == {}          # a directory
    junk = tmp_path / "junk"
    junk.write_text("LOTTERY_ADDRESS=not-an-address\nnonsense\n")
    assert read_address_source(str(junk)) == {}


def test_candidates_put_the_operator_env_first_then_the_file(tmp_path):
    p = tmp_path / "snippet"
    p.write_text(f"LOTTERY_ADDRESS={LIVE}\nHUB_LOTTERY_ADDRESS={OTHER}\n")
    cfg = Config(lottery_address=DEAD, address_file=str(p), hub_lottery_address=DEAD)
    assert cfg.address_candidates() == [DEAD, LIVE, OTHER]
    # …and the same address named twice is offered once.
    cfg2 = Config(lottery_address=LIVE, address_file=str(p))
    assert cfg2.address_candidates() == [LIVE, OTHER]


# ── re-binding mid-flight ─────────────────────────────────────────────────────────────
def _engine(code_at: set[str], cfg: Config, address: str) -> SimpleNamespace:
    """An engine stub with just enough surface for the address guard."""
    def get_code(addr):
        return b"\x60\x80" if str(addr).lower() in {a.lower() for a in code_at} else b""

    return SimpleNamespace(
        cfg=cfg,
        chain=SimpleNamespace(
            address=address,
            w3=SimpleNamespace(eth=SimpleNamespace(get_code=get_code)),
        ),
        sponsor=SimpleNamespace(resolve_bound=MagicMock(
            return_value=SimpleNamespace(ok=True, address=None, reason="stub"))),
        binding=SimpleNamespace(ok=True, address=DEAD, reason="startup"),
        stalled_rounds=[3, 4],
        contract_live=True,
        _last_address_check=0.0,
        _event=MagicMock(),
    )


def _bind(stub):
    """Bind the real methods under test to the stub."""
    stub._has_code = lambda addr: EconomyEngine._has_code(stub, addr)
    stub._rebind = lambda addr: EconomyEngine._rebind(stub, addr)
    return stub


def test_rebinds_when_the_chain_redeployed_the_lottery(tmp_path):
    snippet = tmp_path / "hub.env.snippet"
    snippet.write_text(f"LOTTERY_ADDRESS={LIVE}\nHUB_LOTTERY_ADDRESS={LIVE}\n")
    cfg = Config(lottery_address=DEAD, hub_lottery_address=DEAD, address_file=str(snippet),
                 rpc_url="http://127.0.0.1:8545", address_recheck_s=0.0)
    stub = _bind(_engine(code_at={LIVE}, cfg=cfg, address=DEAD))

    assert EconomyEngine._ensure_contract_live(stub) is True
    assert stub.chain.address.lower() == LIVE            # now driving the live contract
    assert stub.cfg.lottery_address.lower() == LIVE
    # the Hub's binding follows only because the SAME file named it — and the anti-redirect
    # gate is re-resolved against the new address rather than left asserting the old one.
    assert stub.cfg.hub_lottery_address.lower() == LIVE
    stub.sponsor.resolve_bound.assert_called_once()
    # rounds abandoned on the dead contract mean nothing on the new one
    assert stub.stalled_rounds == []
    assert stub.contract_live is True


def test_a_stale_env_alone_cannot_redirect_the_hub_binding(tmp_path):
    """The new address came from the file, but that file does NOT name it as the Hub's
    bound lottery — so the donation target stays where the operator put it (anti-redirect)."""
    snippet = tmp_path / "snippet"
    snippet.write_text(f"LOTTERY_ADDRESS={LIVE}\nHUB_LOTTERY_ADDRESS={OTHER}\n")
    cfg = Config(lottery_address=DEAD, hub_lottery_address=DEAD, address_file=str(snippet),
                 rpc_url="http://127.0.0.1:8545", address_recheck_s=0.0)
    stub = _bind(_engine(code_at={LIVE}, cfg=cfg, address=DEAD))

    assert EconomyEngine._ensure_contract_live(stub) is True
    assert stub.chain.address.lower() == LIVE
    assert stub.cfg.hub_lottery_address == DEAD


def test_an_rpc_blip_is_not_a_redeploy(tmp_path):
    cfg = Config(lottery_address=DEAD, address_file=str(tmp_path / "none"),
                 rpc_url="http://127.0.0.1:8545", address_recheck_s=0.0)
    stub = _bind(_engine(code_at=set(), cfg=cfg, address=DEAD))

    def boom(addr):
        raise ConnectionError("RPC unreachable")

    stub.chain.w3.eth.get_code = boom
    assert EconomyEngine._ensure_contract_live(stub) is True
    assert stub.chain.address == DEAD          # kept, not abandoned
    assert stub.contract_live is True


def test_refuses_to_drive_rounds_when_no_candidate_holds_code(tmp_path):
    snippet = tmp_path / "snippet"
    snippet.write_text(f"LOTTERY_ADDRESS={OTHER}\n")
    cfg = Config(lottery_address=DEAD, address_file=str(snippet),
                 rpc_url="http://127.0.0.1:8545", address_recheck_s=0.0)
    stub = _bind(_engine(code_at=set(), cfg=cfg, address=DEAD))

    assert EconomyEngine._ensure_contract_live(stub) is False
    assert stub.contract_live is False         # /healthz turns 503 instead of "ok"
    assert stub.chain.address == DEAD


def test_the_check_is_rate_limited_but_forceable(tmp_path):
    cfg = Config(lottery_address=DEAD, address_file=str(tmp_path / "none"),
                 rpc_url="http://127.0.0.1:8545", address_recheck_s=3600.0)
    stub = _bind(_engine(code_at=set(), cfg=cfg, address=DEAD))
    calls = []
    stub.chain.w3.eth.get_code = lambda addr: calls.append(addr) or b""

    assert EconomyEngine._ensure_contract_live(stub) is False   # first call always checks
    assert EconomyEngine._ensure_contract_live(stub) is True    # inside the interval: skipped
    assert len(calls) == 1
    assert EconomyEngine._ensure_contract_live(stub, force=True) is False
    assert len(calls) == 2


def test_a_round_never_runs_against_a_dead_address():
    stub = SimpleNamespace(
        _ensure_contract_live=lambda: False,
        open_round=MagicMock(),
        publish=MagicMock(),
        stalled_rounds=[],
    )
    EconomyEngine.run_one_round(stub)
    stub.open_round.assert_not_called()
    stub.publish.assert_not_called()
